In [5]:
import numpy as num
x=num.array([[1,2,3],[4,5,6],[7,8,9]])
y=num.array([[5,2,3],[2,7,7],[9,6,4]])
print("array1")
print(x)
print("array2")
print(y)
print("multiplication of arrays of same size")
print(num.multiply(x,y))

array1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2
[[5 2 3]
 [2 7 7]
 [9 6 4]]
multiplication of arrays of same size
[[ 5  4  9]
 [ 8 35 42]
 [63 48 36]]
