In [52]:
import numpy as nup
array=nup.random.randint(100,size=(4,4))
print(array)
print("After swapping the first and last rows")
array[[3,0]]=array[[0,3]]
print(array)



[[15 64 63 35]
 [32 23 51 33]
 [21 39 51 41]
 [47  5 55 73]]
After swapping the first and last rows
[[47  5 55 73]
 [32 23 51 33]
 [21 39 51 41]
 [15 64 63 35]]
