In [3]:
import numpy as nup
array1=[]
r=int(input("Enter row size :"))
c=int(input("Enter column size :"))
for i in range(r):
    for j in range(c):
        array1.append(int(input("element:")))
array1=nup.array(array1).reshape(r,c)
print(array1)
print("Trace of the  matrix:",nup.trace(array1))

Enter row size :3
Enter column size :3
element:1
element:4
element:5
element:6
element:7
element:89
element:0
element:1
element:2
[[ 1  4  5]
 [ 6  7 89]
 [ 0  1  2]]
Trace of the  matrix: 10
