In [9]:
import numpy as nup
array1=[]
r=int(input("Enter row size :"))
c=int(input("Enter column size :"))
for i in range(r):
    for j in range(c):
        array1.append(int(input("element:")))
array1=nup.array(array1).reshape(r,c)
print(array1)
print("Determinant of the matrix:",nup.linalg.det(array1))

Enter row size :3
Enter column size :3
element:9
element:2
element:1
element:5
element:-1
element:6
element:4
element:0
element:-2
[[ 9  2  1]
 [ 5 -1  6]
 [ 4  0 -2]]
Determinant of the matrix: 90.0
