In [8]:
import numpy as nup
array1=[]
r=int(input("Enter row size :"))
c=int(input("Enter column size :"))
for i in range(r):
    for j in range(c):
        array1.append(int(input("element:")))
array1=nup.array(array1).reshape(r,c)
print(array1)
print("eigen values and eigenvectors are:")
w, v = nup.linalg.eig(array1)
print(w)
print(v)

Enter row size :3
Enter column size :3
element:1
element:2
element:9
element:12
element:11
element:2
element:0
element:0
element:4
[[ 1  2  9]
 [12 11  2]
 [ 0  0  4]]
eigen values and eigenvectors are:
[-1. 13.  4.]
[[-0.70710678 -0.16439899  0.43375318]
 [ 0.70710678 -0.98639392 -0.83809937]
 [ 0.          0.          0.3308287 ]]
