In [3]:
import numpy as nup
array1=[]
r=int(input("Enter row size :"))
c=int(input("Enter column size :"))
for i in range(r):
    for j in range(c):
        array1.append(int(input("element:")))
array1=nup.array(array1).reshape(r,c)
print(array1)
print("Inverse of a matrix is")
print(nup.linalg.inv(array1))

Enter row size :3
Enter column size :3
element:1
element:3
element:-2
element:-3
element:0
element:-5
element:2
element:5
element:0
[[ 1  3 -2]
 [-3  0 -5]
 [ 2  5  0]]
Inverse of a matrix is
[[ 1.   -0.4  -0.6 ]
 [-0.4   0.16  0.44]
 [-0.6   0.04  0.36]]
